# Generated by Django 2.1.8 on 2019-05-05 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
